Corrigido tabulações
andreldm/guessit-backend pull request #13
Opened 2016-10-05 17:00 UTC by geanpeixoto

2016-10-05 20:10 UTC, andreldm requested changes

2016-10-05 20:10 UTC, andreldm commented on package.json
> +    "make-frontend": "cd frontend && npm install && git submodule init && git submodule update && gulp build && cp -R index.html config.js dist jspm_packages ../public"
Melhor evitar esses comandos de submodule nesse momento e colocar:
`git submodule update --init --recursive`

... no README. Não testei pra saber se resolve.

2016-10-06 16:48 UTC, geanpeixoto reviewed
Mudanças realizadas.

2016-10-07 02:29 UTC, andreldm approved these changes

2016-10-07 02:29 UTC, merged